//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forex_Update.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promocode
    {
        public int Id { get; set; }
        public string PromocodeStr { get; set; }
        public string BtcWallet { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
