//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forex_Update.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<double> DepositAmount { get; set; }
        public string UserEmail { get; set; }
        public string UserPhone { get; set; }
        public string UserBTCWallet { get; set; }
        public string RequestDate { get; set; }
        public Nullable<double> DepositAmountBTC { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
