//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forex_Update.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TotalShare
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string name { get; set; }
        public string Symbol { get; set; }
        public decimal TotalVolume { get; set; }
        public decimal TotalPayedAmount { get; set; }
        public string Obj { get; set; }
        public decimal LivePrice { get; set; }
        public decimal PL { get; set; }
    }
}
