//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forex_Update.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trading
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Type { get; set; }
        public decimal Openprice { get; set; }
        public decimal CurrentPrice { get; set; }
        public string Name { get; set; }
        public string Symbol { get; set; }
        public decimal SharePart { get; set; }
        public decimal TotalPayedAmount { get; set; }
        public decimal Profit { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> BuyTime { get; set; }
        public string Obj { get; set; }
    }
}
