//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forex_Update.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Withdrawal
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string UseEmail { get; set; }
        public string SSN { get; set; }
        public string DateOfBirth { get; set; }
        public string PaymentMethod { get; set; }
        public string City { get; set; }
        public string Phone { get; set; }
        public string PostalCode { get; set; }
        public string PromoCode { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<double> Amount { get; set; }
    }
}
